{% set version = "0.8.3" %}

package:
  name: pandas-openscm-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pandas-openscm/pandas_openscm-{{ version }}.tar.gz
  sha256: fdf015906ad2bde4b4db57ff5dd45d5cb694ad9348d54447397fc9e2c2451635

build:
  number: 0

requirements:
  host:
    - python

outputs:
  - name: pandas-openscm
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - pdm-backend
        - pip

      run:
        - python >={{ python_min }}
        - attrs >=24.3.0
        - numpy >=1.25.0
        - pandas >=2.2.0

    test:
      imports:
        - pandas_openscm
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: pandas-openscm-locked
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pdm-backend
        - pip

      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('pandas-openscm', exact=True) }}
        - {{ pin_compatible('attrs', lower_bound='24.3.0', upper_bound='24.3.1') }}
        - {{ pin_compatible('numpy', lower_bound='2.0.2', upper_bound='2.2.5') }}
        - {{ pin_compatible('pandas', lower_bound='2.2.3', upper_bound='2.2.4') }}

    test:
      imports:
        - pandas_openscm
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://pandas-openscm.readthedocs.io
  summary: Pandas accessors for OpenSCM-related functionality.
  description: |
    Pandas accessors for OpenSCM-related functionality.
    It is provided, by default, as a library.
    If you wish to use it as an application,
    we recommend installing the locked version of the package,
    i.e. `pandas-openscm-locked`,
    because this pins the versions of key dependencies
    (which avoids breakages because of updates to dependencies).
  license: BSD-3-Clause
  license_file: LICENCE
  doc_url: https://pandas-openscm.readthedocs.io
  dev_url: https://github.com/openscm/pandas-openscm

extra:
  feedstock-name: pandas-openscm
  recipe-maintainers:
    - znicholls
